# Generated by Django 5.1.15 on 2026-06-03 17:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("campaigns", "0001_initial"),
        ("items", "0001_initial"),
        ("warehouses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Count",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_recount", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("SUBMITTED", "Submitted")],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counts",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "parent_count",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recounts",
                        to="counts.count",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counts",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CountLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("qty_units", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("qty_packs", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ("total_units", models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ("flagged_for_recount", models.BooleanField(default=False)),
                ("line_uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("version", models.IntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="counts.count",
                    ),
                ),
                (
                    "counted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="count_lines",
                        to="accounts.fielduser",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="count_lines",
                        to="items.item",
                    ),
                ),
            ],
            options={
                "ordering": ["item__item_code"],
                "indexes": [
                    models.Index(
                        fields=["line_uid", "version"], name="counts_coun_line_ui_41da8a_idx"
                    )
                ],
            },
        ),
    ]
