# Generated by Django 5.1.15 on 2026-06-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("whs_code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["whs_code"],
            },
        ),
    ]
