# Generated by Django 5.1.15 on 2026-06-03 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("items", "0001_initial"),
        ("warehouses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CsvExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("file_ref", models.CharField(blank=True, max_length=255)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="csv_exports",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="csv_exports",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="Reconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value_margin", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ("set_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("COMPLETED", "Completed")],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliations",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliations",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReconciliationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("physical_qty", models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ("system_qty", models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ("gap_qty", models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ("physical_value", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ("system_value", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ("gap_value", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ("within_margin", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation_lines",
                        to="items.item",
                    ),
                ),
                (
                    "reconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="reconciliation.reconciliation",
                    ),
                ),
            ],
            options={
                "ordering": ["item__item_code"],
            },
        ),
        migrations.CreateModel(
            name="SignOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("agent_signed", models.BooleanField(default=False)),
                ("warehouseman_signed", models.BooleanField(default=False)),
                ("document", models.FileField(blank=True, null=True, upload_to="signoffs/")),
                ("received", models.BooleanField(default=False)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signoffs",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signoffs",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("system_qty", models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ("unit_value", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_stock",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="system_stock",
                        to="items.item",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_stock",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="reconciliation",
            constraint=models.UniqueConstraint(
                fields=("campaign", "warehouse"), name="uniq_reconciliation"
            ),
        ),
        migrations.AddConstraint(
            model_name="signoff",
            constraint=models.UniqueConstraint(
                fields=("campaign", "warehouse"), name="uniq_signoff"
            ),
        ),
        migrations.AddConstraint(
            model_name="systemstock",
            constraint=models.UniqueConstraint(
                fields=("campaign", "warehouse", "item"), name="uniq_system_stock"
            ),
        ),
    ]
