# Generated by Django 5.1.15 on 2026-06-03 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("warehouses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly"), ("PERIOD", "Period / ad-hoc")],
                        default="MONTHLY",
                        max_length=10,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("HIGH_GAP", "High gap"),
                            ("ANOMALY", "Anomaly"),
                        ],
                        default="ROUTINE",
                        max_length=10,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("ALL", "All warehouses"), ("SPECIFIC", "Specific warehouses")],
                        default="ALL",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ARMED", "Armed"),
                            ("OPEN", "Open"),
                            ("RECOUNT", "Re-count"),
                            ("CLOSED", "Closed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("open_at", models.DateTimeField(blank=True, null=True)),
                ("close_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignWarehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_warehouses",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="warehouses.warehouse"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="campaign",
            name="warehouses",
            field=models.ManyToManyField(
                related_name="campaigns",
                through="campaigns.CampaignWarehouse",
                to="warehouses.warehouse",
            ),
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("confirmed", models.BooleanField(default=False)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "field_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="accounts.fielduser",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="warehouses.warehouse"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "warehouse", "field_user"), name="uniq_assignment"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("pin_hash", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="accounts.fielduser",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("field_user", "campaign"), name="uniq_agent_credential"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="campaignwarehouse",
            constraint=models.UniqueConstraint(
                fields=("campaign", "warehouse"), name="uniq_campaign_warehouse"
            ),
        ),
    ]
