# Generated by Django 5.1.15 on 2026-06-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("item_code", models.CharField(max_length=60)),
                ("sku", models.CharField(max_length=60)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("color_parfum", models.CharField(blank=True, max_length=120)),
                ("base_unit", models.CharField(default="unit", max_length=20)),
                ("units_per_pack", models.PositiveIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["item_code", "sku"],
                "constraints": [
                    models.UniqueConstraint(fields=("item_code", "sku"), name="uniq_item_code_sku")
                ],
            },
        ),
    ]
